# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_pt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pt.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_pt.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_pt.setObjectName("pushButton_pt")
        self.gridLayout.addWidget(self.pushButton_pt, 6, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.buttonGroup_numbers = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_numbers.setObjectName("buttonGroup_numbers")
        self.buttonGroup_numbers.addButton(self.pushButton_5)
        self.gridLayout.addWidget(self.pushButton_5, 5, 2, 1, 1)
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main_label.setFont(font)
        self.main_label.setText("")
        self.main_label.setObjectName("main_label")
        self.gridLayout.addWidget(self.main_label, 1, 1, 1, 4)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_1.setObjectName("pushButton_1")
        self.buttonGroup_numbers.addButton(self.pushButton_1)
        self.gridLayout.addWidget(self.pushButton_1, 3, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup_numbers.addButton(self.pushButton_3)
        self.gridLayout.addWidget(self.pushButton_3, 4, 2, 1, 1)
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_open.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout.addWidget(self.pushButton_open, 2, 0, 1, 2)
        self.pushButton_history = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_history.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_history.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_history.setObjectName("pushButton_history")
        self.gridLayout.addWidget(self.pushButton_history, 3, 4, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_minus.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.buttonGroup_operators2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_operators2.setObjectName("buttonGroup_operators2")
        self.buttonGroup_operators2.addButton(self.pushButton_minus)
        self.gridLayout.addWidget(self.pushButton_minus, 3, 0, 1, 2)
        self.pushButton_stepen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stepen.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_stepen.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_stepen.setObjectName("pushButton_stepen")
        self.buttonGroup_operators2.addButton(self.pushButton_stepen)
        self.gridLayout.addWidget(self.pushButton_stepen, 4, 4, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.buttonGroup_numbers.addButton(self.pushButton_8)
        self.gridLayout.addWidget(self.pushButton_8, 6, 3, 1, 1)
        self.pushButton_eq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eq.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_eq.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.gridLayout.addWidget(self.pushButton_eq, 7, 4, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_0.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_0.setObjectName("pushButton_0")
        self.buttonGroup_numbers.addButton(self.pushButton_0)
        self.gridLayout.addWidget(self.pushButton_0, 7, 3, 1, 1)
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_back.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_back.setObjectName("pushButton_back")
        self.gridLayout.addWidget(self.pushButton_back, 2, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup_numbers.addButton(self.pushButton_2)
        self.gridLayout.addWidget(self.pushButton_2, 3, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.buttonGroup_numbers.addButton(self.pushButton_6)
        self.gridLayout.addWidget(self.pushButton_6, 5, 3, 1, 1)
        self.pushButton_split = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_split.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_split.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_split.setObjectName("pushButton_split")
        self.buttonGroup_operators2.addButton(self.pushButton_split)
        self.gridLayout.addWidget(self.pushButton_split, 5, 0, 1, 2)
        self.pushButton_multi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multi.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_multi.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_multi.setObjectName("pushButton_multi")
        self.buttonGroup_operators2.addButton(self.pushButton_multi)
        self.gridLayout.addWidget(self.pushButton_multi, 4, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup_numbers.addButton(self.pushButton_4)
        self.gridLayout.addWidget(self.pushButton_4, 4, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_9.setObjectName("pushButton_9")
        self.buttonGroup_numbers.addButton(self.pushButton_9)
        self.gridLayout.addWidget(self.pushButton_9, 7, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.buttonGroup_numbers.addButton(self.pushButton_7)
        self.gridLayout.addWidget(self.pushButton_7, 6, 2, 1, 1)
        self.pushButton_koren = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_koren.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_koren.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_koren.setObjectName("pushButton_koren")
        self.buttonGroup_operarors1 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_operarors1.setObjectName("buttonGroup_operarors1")
        self.buttonGroup_operarors1.addButton(self.pushButton_koren)
        self.gridLayout.addWidget(self.pushButton_koren, 6, 0, 1, 2)
        self.pushButton_factorial = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_factorial.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_factorial.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_factorial.setObjectName("pushButton_factorial")
        self.buttonGroup_operarors1.addButton(self.pushButton_factorial)
        self.gridLayout.addWidget(self.pushButton_factorial, 5, 4, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_plus.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.buttonGroup_operators2.addButton(self.pushButton_plus)
        self.gridLayout.addWidget(self.pushButton_plus, 7, 0, 1, 2)
        self.pushButton_clean = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clean.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_clean.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.gridLayout.addWidget(self.pushButton_clean, 2, 3, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_close.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Ответ:"))
        self.pushButton_pt.setText(_translate("MainWindow", "."))
        self.label.setText(_translate("MainWindow", "Калькулятор"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_open.setText(_translate("MainWindow", "("))
        self.pushButton_history.setText(_translate("MainWindow", "history"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_stepen.setText(_translate("MainWindow", "**"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_eq.setText(_translate("MainWindow", "="))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_back.setText(_translate("MainWindow", "back"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_split.setText(_translate("MainWindow", "/"))
        self.pushButton_multi.setText(_translate("MainWindow", "*"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_koren.setText(_translate("MainWindow", "√"))
        self.pushButton_factorial.setText(_translate("MainWindow", "!"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_clean.setText(_translate("MainWindow", "C"))
        self.pushButton_close.setText(_translate("MainWindow", ")"))
